language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mahi153/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mahi153/docker-react npm run test -- --coverage